models_list = [
    {
        "id": "claude-instant-1.2",
        "object": "model",
        "owned_by": "Anthropic",
        "context_window": "100K",
        "Multilingual": True,
        "vision": False,
        "description": "Our cheapest small and fast model, a predecessor of Claude Haiku",
    },
    {
        "id": "claude-2.1",
        "object": "model",
        "owned_by": "Anthropic",
        "context_window": "200K",
        "Multilingual": True,
        "vision": False,
        "description": "Updated version of Claude 2 with improved accuracy",
    },
    {
        "id": "claude-3-5-sonnet-20240620",
        "object": "model",
        "owned_by": "Anthropic",
        "context_window": "200K",
        "Multilingual": True,
        "vision": True,
        "description": "Most intelligent model",
    },
    {
        "id": "claude-3-opus-20240229",
        "object": "model",
        "owned_by": "Anthropic",
        "context_window": "200K",
        "Multilingual": True,
        "vision": True,
        "description": "Powerful model for highly complex tasks",
    },
    {
        "id": "claude-3-sonnet-20240229",
        "object": "model",
        "owned_by": "Anthropic",
        "context_window": "200K",
        "Multilingual": True,
        "vision": True,
        "description": "Balance of intelligence and speed",
    },
    {
        "id": "claude-3-haiku-20240307",
        "object": "model",
        "owned_by": "Anthropic",
        "context_window": "200K",
        "multilingual": True,
        "vision": True,
        "description": "Fastest and most compact model for near-instant responsiveness",
    },
]